server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/5619db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 269929756@qq.com
    password: hpktqfiybohfcahb
    port: 465
    protocol: smtps
    default-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        new_generator_mappings: false
        format_sql: true
    show-sql: true
    generate-ddl: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

upload:
  path: Desktop/ELEC5619