server:
  port: 8085
  servlet:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/5619db?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 269929756@qq.com
    password: akujmmlodiwebiig
    port: 465
    protocol: smtps
    default-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        new_generator_mappings: false
        format_sql: true
    show-sql: true



