server:
  port: 8085
  servlet:
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 269929756@qq.com
    password: hnrzzifehxcpcbdh
    port: 465
    protocol: smtps
    default-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        new_generator_mappings: false
        format_sql: true
    show-sql: true



